name: Confluence
description: |
  Confluence based on Alpine with a PostgreSQL database. This build is meant to be
  behind a Traefik proxy.
version: v0.1.0
category: CMS
maintainer: LasLabs Inc. <support@laslabs.com>
license: Apache 2.0
projectURL: https://github.com/LasLabs/rancher-catalog
