---
version: '2'
volumes:
  jira-jre-security-data:
    driver: ${VOLUME_DRIVER}
  jira-home-data:
    driver: ${VOLUME_DRIVER}
  jira-install-data:
    driver: ${VOLUME_DRIVER}
  jira-db-data:
    driver: ${VOLUME_DRIVER}
services:
  jira-server:
    image: laslabs/alpine-jira:7.6.2
    volumes:
    - jira-home-data:/var/atlassian/jira
    - jira-log-data:/opt/atlassian/jira/logs
    - jira-jre-security-data:/usr/lib/jvm/java-1.8-openjdk/jre/lib/security
    - jira-install-conf-data:/opt/atlassian/jira/conf
    labels:
      {{- if ne .Values.TRAEFIK_DOMAIN "" }}
      traefik.domain: "${TRAEFIK_DOMAIN}"
      {{- end }}
      {{- if ne .Values.TRAEFIK_HOST "" }}
      traefik.frontend.rule: 'Host: ${TRAEFIK_HOST}'
      {{- end }}
      traefik.enable: 'true'
      traefik.port: '8080'
      io.rancher.container.pull_image: always
      traefik.frontend.passHostHeader: 'true'
      io.rancher.sidekicks: postgresql
  postgresql:
    image: postgres:9.6-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_USER: ${PSQL_USER}
    volumes:
    - jira-db-data:/var/lib/postgresql/data
