version: "2"

catalog:
  name: JIRA
  version: "v0.1.0"
  description: "JIRA with a PostgreSQL backend. Meant to be proxied by Traefik."
  uuid: vertical-medical-dev-0
  minimum_rancher_version: v1.0.0
  questions:

    - variable: "VOLUME_DRIVER"
      description: "The volume driver to use for persistent storage."
      label: "Volume Driver"
      required: true
      type: "enum"
      default: "local"
      options:
        - local
        - rancher-ebs
        - rancher-efs
        - rancher-nfs

    - variable: "TRAEFIK_DOMAIN"
      description: "Override for the base domain that is defined in Traefik."
      label: "Traefik Domain"
      type: "string"

    - variable: "TRAEFIK_HOST"
      description: "Additional domain name that should be advertised through Traefik."
      label: "Traefik Host"
      type: "string"

    - variable: "PSQL_USER"
      description: "Username to use for the PostgreSQL server."
      label: "PostgreSQL User"
      default: "jira"
      type: "string"
      required: true

    - variable: "PSQL_PASSWORD"
      description: "Password to use for the PostgreSQL server."
      label: "PostgreSQL Password"
      type: "password"
      required: true

services:
  jira-server:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 8080
      unhealthy_threshold: 60
      initializing_timeout: 200000
      interval: 2000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 200000
  postgresql:
    scale: 1
    start_on_create: true
