---
version: '2'

volumes:
  odoo-web-data:
    driver: ${VOLUME_DRIVER}
  odoo-private-addons:
    driver: ${VOLUME_DRIVER}
  {{- if eq .Values.PSQL_SERVICE_NEW "" }}
  odoo-db-data:
    driver: ${VOLUME_DRIVER}
  {{- end }}

services:

  odoo-upgrader-core:
    image: laslabs/odoo-upgrade:9.0
    environment:
      - DB_SOURCE: "${PSQL_DATABASE_OLD}"
      - DB_TARGET: "${PSQL_DATABASE_NEW}"
      - PGDATABASE: "${PSQL_DATABASE_NEW}"
      - PGUSER: "${PSQL_USER}"
      - PGPASSWORD: "${PSQL_PASSWORD}"
    external_links:
    - "${PSQL_SERVICE_OLD}:db_old"
    {{- if ne .Values.PSQL_SERVICE_NEW "" }}
    - "${PSQL_SERVICE_NEW}:db"
    {{- end }}
    {{- if eq .Values.PSQL_SERVICE_NEW "" }}
    links:
    - postgresql:db
    {{- end }}
    volumes:
    - odoo-web-data:/var/lib/odoo
    - odoo-private-addons:/opt/odoo/custom/src/private
    tty: true
    labels:
      io.rancher.container.pull_image: 'always'
      io.rancher.container.start_once: 'true'
    scale: 1
    start_on_create: true

  odoo-upgrader-custom:
    image: "${SCAFFOLD_IMAGE}:${SCAFFOLD_TAG}"
    environment:
      - PGDATABASE: "${PSQL_DATABASE_NEW}"
      - PGUSER: "${PSQL_USER}"
      - PGPASSWORD: "${PSQL_PASSWORD}"
    external_links:
    - "${PSQL_SERVICE_OLD}:db_old"
    {{- if ne .Values.PSQL_SERVICE_NEW "" }}
    - "${PSQL_SERVICE_NEW}:db"
    {{- end }}
    {{- if eq .Values.PSQL_SERVICE_NEW "" }}
    links:
    - postgresql:db
    {{- end }}
    volumes:
    - odoo-web-data:/var/lib/odoo
    - odoo-private-addons:/opt/odoo/custom/src/private
    tty: true
    labels:
      io.rancher.container.pull_image: 'always'
      io.rancher.container.start_once: 'true'
    scale: 1
    start_on_create: true

  {{- if eq .Values.PSQL_SERVICE_NEW "" }}
  postgresql:
    image: postgres:9.6-alpine
    hostname: db
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: "${PSQL_PASSWORD}"
      POSTGRES_USER: "${PSQL_USER}"
    volumes:
    - odoo-db-data-new:/var/lib/postgresql/data/
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 5432
      unhealthy_threshold: 20
      initializing_timeout: 60000
      interval: 5000
      strategy: recreate
      reinitializing_timeout: 60000
  {{- end }}
