name: Mattermost
description: |
  Mattermost is an open source messaging system.
  This build is meant to be behind a Traefik proxy.
version: v0.1.0
category: Chat
maintainer: LasLabs Inc. <support@laslabs.com>
license: Apache 2.0
projectURL: https://github.com/LasLabs/rancher-catalog
