version: '2'

volumes:
  sentry-filestore:
    driver: ${VOLUME_DRIVER}
  {{- if eq .Values.PSQL_SERVICE "" }}
  sentry-db-data:
    driver: ${VOLUME_DRIVER}
  {{- end }}

services:

  sentry-server:
    image: sentry:8.22
    environment:
      SENTRY_DB_NAME: "${PSQL_DB}"
      SENTRY_DB_PASSWORD: "${PSQL_PASSWORD}"
      SENTRY_DB_USER: "${PSQL_USER}"
      SENTRY_EMAIL_HOST: "${SMTP_HOST}"
      SENTRY_EMAIL_PASSWORD: "${SMTP_PASSWORD}"
      SENTRY_EMAIL_PORT: "${SMTP_PORT}"
      SENTRY_EMAIL_USER: "${SMTP_USER}"
      SENTRY_POSTGRES_HOST: "postgresql"
      SENTRY_SECRET_KEY: "${SENTRY_SECRET}"
      SENTRY_SERVER_EMAIL: "${SENTRY_EMAIL}"
    {{- if (or (ne .Values.PSQL_SERVICE "") (ne .Values.REDIS_SERVICE "") ) }}
    external_links:
    {{- end }}
    {{- if ne .Values.PSQL_SERVICE ""}}
    - "${PSQL_SERVICE}:postgresql"
    {{- end }}
    {{- if ne .Values.REDIS_SERVICE ""}}
    - "${REDIS_SERVICE}:redis"
    {{- end }}
    {{- if (or (eq .Values.PSQL_SERVICE "") (eq .Values.REDIS_SERVICE "") ) }}
    links:
    {{- end }}
    {{- if eq .Values.PSQL_SERVICE ""}}
    - postgresql:postgresql
    {{- end }}
    {{- if eq .Values.REDIS_SERVICE ""}}
    - redis:redis
    {{- end }}
    volumes:
    - sentry-filestore:/var/lib/sentry/files
    command:
    - /bin/bash
    - -c
    - sentry upgrade --noinput && sentry createuser --email ${SENTRY_ADMIN_USER} --password ${SENTRY_ADMIN_PASSWORD} --superuser && /entrypoint.sh run web || /entrypoint.sh run web
    labels:
      {{- if ne .Values.TRAEFIK_DOMAIN "" }}
      traefik.domain: "${TRAEFIK_DOMAIN}"
      {{- end }}
      {{- if ne .Values.TRAEFIK_HOST "" }}
      traefik.frontend.rule: 'Host: ${TRAEFIK_HOST}'
      {{- end }}
      traefik.enable: 'true'
      traefik.port: '9000'
      traefik.frontend.passHostHeader: 'true'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 9000
      unhealthy_threshold: 3
      initializing_timeout: 600000
      interval: 2000
      strategy: recreate
      request_line: GET "/auth/login/sentry" "HTTP/1.0"
      reinitializing_timeout: 60000

  sentry-cron:
    image: sentry:8.22
    environment:
      SENTRY_DB_NAME: "${PSQL_DB}"
      SENTRY_DB_PASSWORD: "${PSQL_PASSWORD}"
      SENTRY_DB_USER: "${PSQL_USER}"
      SENTRY_EMAIL_HOST: "${SMTP_HOST}"
      SENTRY_EMAIL_PASSWORD: "${SMTP_PASSWORD}"
      SENTRY_EMAIL_PORT: "${SMTP_PORT}"
      SENTRY_EMAIL_USER: "${SMTP_USER}"
      SENTRY_POSTGRES_HOST: "postgresql"
      SENTRY_SECRET_KEY: "${SENTRY_SECRET}"
      SENTRY_SERVER_EMAIL: "${SENTRY_EMAIL}"
    {{- if (or (ne .Values.PSQL_SERVICE "") (ne .Values.REDIS_SERVICE "") ) }}
    external_links:
    {{- end }}
    {{- if ne .Values.PSQL_SERVICE ""}}
    - "${PSQL_SERVICE}:postgresql"
    {{- end }}
    {{- if ne .Values.REDIS_SERVICE ""}}
    - "${REDIS_SERVICE}:redis"
    {{- end }}
    {{- if (or (eq .Values.PSQL_SERVICE "") (eq .Values.REDIS_SERVICE "") ) }}
    links:
    {{- end }}
    {{- if eq .Values.PSQL_SERVICE ""}}
    - postgresql:postgresql
    {{- end }}
    {{- if eq .Values.REDIS_SERVICE ""}}
    - redis:redis
    {{- end }}
    volumes:
    - sentry-filestore:/var/lib/sentry/files
    command:
    - run
    - cron
    labels:
      io.rancher.container.hostname_override: container_name
    scale: 1
    start_on_create: true

  sentry-worker:
    image: sentry:8.22
    environment:
      SENTRY_DB_NAME: "${PSQL_DB}"
      SENTRY_DB_PASSWORD: "${PSQL_PASSWORD}"
      SENTRY_DB_USER: "${PSQL_USER}"
      SENTRY_EMAIL_HOST: "${SMTP_HOST}"
      SENTRY_EMAIL_PASSWORD: "${SMTP_PASSWORD}"
      SENTRY_EMAIL_PORT: "${SMTP_PORT}"
      SENTRY_EMAIL_USER: "${SMTP_USER}"
      SENTRY_POSTGRES_HOST: "postgresql"
      SENTRY_SECRET_KEY: "${SENTRY_SECRET}"
      SENTRY_SERVER_EMAIL: "${SENTRY_EMAIL}"
    {{- if (or (ne .Values.PSQL_SERVICE "") (ne .Values.REDIS_SERVICE "") ) }}
    external_links:
    {{- end }}
    {{- if ne .Values.PSQL_SERVICE ""}}
    - "${PSQL_SERVICE}:postgresql"
    {{- end }}
    {{- if ne .Values.REDIS_SERVICE ""}}
    - "${REDIS_SERVICE}:redis"
    {{- end }}
    {{- if (or (eq .Values.PSQL_SERVICE "") (eq .Values.REDIS_SERVICE "") ) }}
    links:
    {{- end }}
    {{- if eq .Values.PSQL_SERVICE ""}}
    - postgresql:postgresql
    {{- end }}
    {{- if eq .Values.REDIS_SERVICE ""}}
    - redis:redis
    {{- end }}
    command:
    - run
    - worker
    volumes:
    - sentry-filestore:/var/lib/sentry/files
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.container.hostname_override: container_name
    scale: 1
    start_on_create: true

  {{- if eq .Values.REDIS_SERVICE ""}}
  redis:
    image: redis:4-alpine
    labels:
      io.rancher.container.hostname_override: container_name
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 6379
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
    scale: 1
    start_on_create: true
  {{- end }}

  {{- if eq .Values.PSQL_SERVICE ""}}
  postgresql:
    image: postgres:9.6-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${PSQL_DB}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_USER: ${PSQL_USER}
    volumes:
    - sentry-db-data:/var/lib/postgresql/data
    labels:
      io.rancher.container.hostname_override: container_name
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 5432
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
    scale: 1
    start_on_create: true
  {{- end }}
