---
version: '2'
volumes:
  confluence-jre-security-data:
    driver: ${VOLUME_DRIVER}
  confluence-home-data:
    driver: ${VOLUME_DRIVER}
  confluence-install-data:
    driver: ${VOLUME_DRIVER}
  confluence-db-data:
    driver: ${VOLUME_DRIVER}
services:
  confluence-server:
    image: laslabs/alpine-confluence:6.6.0
    volumes:
    - confluence-home-data:/var/atlassian/confluence
    - confluence-log-data:/opt/atlassian/confluence/logs
    - confluence-jre-security-data:/usr/lib/jvm/java-1.8-openjdk/jre/lib/security
    - confluence-install-conf-data:/opt/atlassian/confluence/conf
    labels:
      {{- if ne .Values.TRAEFIK_DOMAIN "" }}
      traefik.domain: "${TRAEFIK_DOMAIN}"
      {{- end }}
      {{- if ne .Values.TRAEFIK_HOST "" }}
      traefik.frontend.rule: 'Host: ${TRAEFIK_HOST}'
      {{- end }}
      traefik.enable: 'true'
      traefik.port: '8090'
      io.rancher.container.pull_image: always
      traefik.frontend.passHostHeader: 'true'
      io.rancher.sidekicks: postgresql
  postgresql:
    image: postgres:9.6-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_USER: ${PSQL_USER}
    volumes:
    - confluence-db-data:/var/lib/postgresql/data
